### ISSUE TITLE
[Question] Using Switch inside of a Frame

### ISSUE THREAD

**Issue by antongit** [tisho/Switch.framerfx#17] opened 2020-12-03 12:10 UTC
Hello Tischo,

am I right, that the Switch is working only when it's placed directly on the Canvas?
I have to create a Component from Design, for that I have to nest evertyhing into one Frame. But placing the Switch into a Frame breaks all the connections and it's not possible to make any of them again.

Is it possible to make the Switch to work inside of a Frame or this is something which is technically not doable and the Swich works only on the Canvas itself?

Thanks,
Anton

**Comment by tisho** [comment] 2020-12-18 02:10
You shouldn't have any problems using Switch inside a Frame. This is what a lot of the examples in the example project already do. Can you provide a file or link to a Framer Web project that reproduces this problem?

**Comment by antongit** [comment] 2020-12-18 09:15
Let me explain this a bit better.
I'm talking about nesting the Switch and a frame-to-switch-to inside another Frame.
The reason for that: it is the only way to convert the whole thing into the Component, right? Or am I totally wrong?
We need it so much, because we have a big project here and we definitely need to pack pieces of it into individual Components, so we can develop them individually, reuse them and manage the whole thing better.

Framer project is attached below.

<img width="558" alt="Screenshot 2020-12-18 at 10 03 58" src="https://user-images.githubusercontent.com/1189037/102596186-19563500-4119-11eb-9b25-f683a092f126.png">

[SwitchContainerDemo.framerx.zip](https://github.com/tisho/Switch.framerfx/files/5714738/SwitchContainerDemo.framerx.zip)

**Comment by tisho** [comment] 2020-12-18 17:41
I see what you're saying. Framer doesn't support connecting components to children that are part of the same container. However that doesn't prevent you from keeping the connected frames outside. When you then convert the container to a design component, the switch inside will stay connected to the frames outside. When you then create an instance of that component, the connections should be preserved.

I should note that reusability via design components hasn't really been a goal for Switch. Design components are too limited in terms of functionality for this to be an easy and performant solution. What I'd encourage you to try, instead, is the new Variants & Variables Beta we released in Framer Web last week. The feature was created with reusability in mind, and it should soon be able to do everything Switch does and more.

I'll close this issue since there's no action I can really take here, but you're welcome to continue the discussion in this thread.

**Closed as completed by tisho** 2020-12-18 17:41 UTC

**Comment by antongit** [comment] 2020-12-19 16:59
Hi Tisho,

thank you for the answer.
I was trying the Beta on Wednesday and I've found that it was not possible to use any components inside of the Variant (even the things like Button or Toggle). I guess this is just the current state? Do you have any ETA of the Variant Feature? Or at least when will it be more mature?
